dist: xenial

language: rust
rust:
  - 1.35.0
cache:
  - cargo

branches:
  only:
    - master
    # GitHub release tags (for example "v0.9" or "v0.9.1").
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    # Branch names endings with "-release" (for example "0.9.0-release").
    - /-release$/
stages:
  - test

env:
  global:
    - RUSTFLAGS="-D warnings"

jobs:
  include:
    - stage: test
      install:
        - rustup component add rustfmt
        - rustfmt -V
        - rustup component add clippy
        - cargo clippy -V
      script:
        - cargo fmt --all -- --check
        - cargo clippy --all --lib --tests -- -D warnings
        - cargo test --all
